# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - main
      - github-actions-config
  workflow_dispatch:

jobs:
  build-and-test:
    if: github.event_name == 'pull_request'
    name: Test on node ${{ matrix.os }} and ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: 'echo "$TEST" > key'
        shell: bash
        env:
          TEST: ${{secrets.TEST}}
      - run: 'echo "$Test_ci" > key'
        shell: bash
        env:
          Test_ci: ${{secrets.Test_ci}}
      - run: 'echo "$TEST" > key'
        shell: bash
        env:
          TEST: ${{secrets.Test_ci.TEST}}
      - run: 'echo "$TEST" > key'
        shell: bash
        env:
          TEST: ${{Test_ci.Test_ci}}
      - run: npm run test:unit