# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - main
      - github-actions-config
  workflow_dispatch:
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x, 20.x]
    runs-on: ${{ matrix.os }}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test:unit